channels:
  - pytorch
  - conda-forge
name: ml-tutorials
dependencies:
  - conda
  - cudatoolkit=10.2
  - ipywidgets
  - jupyterlab
  - matplotlib
  - numpy
  - opencv-python
  - pip
  - python=3.8
  - pytorch=1.7
  - pytorch-lightning
  - tensorboard
  - torchvision
  - tqdm
